### ISSUE TITLE
Take DefaultTheme type from styled-components

### ISSUE THREAD

**Issue by Vidlec** [qest-cz/style-helpers#1]
styled-components docs says:
```
TypeScript definitions for styled-components can be extended by using declaration merging since version v4.1.4 of the definitions.
```

I suggest to use this approach and eliminate the need for re-exporting functions just for types
https://www.styled-components.com/docs/api#typescript

**Comment by Giboork** [comment]
It might be in the doc, but if I prefer to drop the unnecessary `types` file, in favor of helpers, since you can just call `createStyleHelpers<typeof theme>` and have full definition that is self maintained, and you dont have to "register" new color to extra file.
